// <auto-generated />
namespace Jop_Offers_Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Jobtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Jobtable));
        
        string IMigrationMetadata.Id
        {
            get { return "202107211527142_Jobtable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
